# fly.toml app configuration file generated for garry on 2024-05-02T17:19:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'garry'

[build]
  dockerfile = 'fly.dockerfile'

[deploy]
  strategy = 'immediate'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 1000000
    soft_limit = 800000

[[services]]
  protocol = "udp"
  internal_port = 1992

  [[services.ports]]
    port = 1992


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
